name: Rails Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3
          
      - name: Wait for PostgreSQL to become ready
        run: sleep 5

      - name: Set up Database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_test_database
          POSTGRES_PORT: 5432
        run: |
          bin/rails db:create db:schema:load

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
